name: Build Windows Executable

on:
  push:
    tags:
      - "v*.*.*" # Gera um release apenas para tags versionadas (ex: v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Construir executável
        run: |
          pyinstaller --onefile --windowed --icon=setup/icon.ico main.py

      - name: Criar artefato
        uses: actions/upload-artifact@v3
        with:
          name: EditorRadio.exe
          path: dist/main.exe

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: dist/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
