name: Build and Release Setup

on:
  push:
    tags:
      - "v*.*.*" # Gera um release apenas para tags versionadas (ex: v1.0.0)

permissions:
    contents: write
      
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Enviar instalador para o release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/EditorRadio_Setup_v*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
